# Generated by Django 5.2.9 on 2026-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_booking_razorpay_order_id_booking_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
